// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement__7 = "CgkI-5KggP8LEAIQBg"; // <GPGSID>
        public const string achievement_60 = "CgkI-5KggP8LEAIQAw"; // <GPGSID>
        public const string achievement_100 = "CgkI-5KggP8LEAIQBQ"; // <GPGSID>
        public const string leaderboard = "CgkI-5KggP8LEAIQCg"; // <GPGSID>
        public const string achievement__7_3 = "CgkI-5KggP8LEAIQCA"; // <GPGSID>
        public const string achievement_80 = "CgkI-5KggP8LEAIQBA"; // <GPGSID>
        public const string achievement_40 = "CgkI-5KggP8LEAIQAg"; // <GPGSID>
        public const string achievement__7_2 = "CgkI-5KggP8LEAIQBw"; // <GPGSID>
        public const string achievement__7_4 = "CgkI-5KggP8LEAIQCQ"; // <GPGSID>
        public const string achievement_20 = "CgkI-5KggP8LEAIQAQ"; // <GPGSID>

}

